### PR TITLE
Implement .more for check_mail

### PR DESCRIPTION
**Pull request by Androbin**
Towards #159
See https://github.com/goavki/phenny/issues/259#issuecomment-354063287 for reference

### CODE REVIEW

**Comment by wei2912** [comment]
Why were changes to git.py made?

**Comment by Androbin** [comment]
> Why were changes to git.py made?

Oops, I seem to have carried them over to this branch...

**Comment by wei2912** [comment]
Also, the functions added to more.py are just variants of add_messages, and having so many functions do the same function isn't good practice. Could you leave the more module unchanged?

**Comment by Androbin** [comment]
They are simply helper functions for dealing with multiple channels.
See `git.py` and `mailing_list.py` for reference.

**Comment by Androbin** [comment]
@wei2912 Are you okay with the changes now?

**Comment by shardulc** [comment]
Looks good to me, but seeing it in action is always nice. @Androbin Do you think it is a lot of effort to get a test mailing list config up?

**Comment by Androbin** [comment]
I have tried to do so, but I fear I can't.

**Comment by Androbin** [comment]
Would you be satisfied if I were to mock `unseen_mails`, `rc`, `data` and `e` ?

**Comment by Androbin** [comment]
Besides, there isn't all too much room for it to fail anyway.

**Comment by Androbin** [comment]
screenshot

**Comment by Androbin** [comment]
@wei2912 Can you take over from @shardulc? He's busy.

**Comment by Androbin** [comment]
These mails are mocks, but as close to real ones as possible.

**Comment by Androbin** [comment]
Besides, there isn't much room to break something with this changeset.

**Comment by sushain97** [comment]
Counted as part of GCI task https://codein.withgoogle.com/dashboard/task-instances/4764436512374784/

**Pull request merged**
