### PR TITLE
Fix clock.py issues

### PR DESCRIPTION
**Pull request by Androbin**

### CODE REVIEW

**Comment by Androbin** [comment]
@shardulc Seems like the CI tests didn't catch these ;)

**Comment by shardulc** [comment]
Because the tests are disabled because it is apparently tricky to configure databases on Travis. :)

**Comment by Androbin** [comment]
> it is apparently tricky to configure databases on Travis. :)

Yeah, noticed that when writing some (database-backed) tests myself...

**Comment by Androbin** [comment]
See #319 for that one.

**Comment by shardulc** [comment]
I did try to verify the changes to `clock.py` last time, and they seemed to work... can you test these changes too, deleting any existing databases your system may have and running phenny?

**Comment by Androbin** [comment]
Have done so before sending the PR.

**Comment by shardulc** [comment]
Can you look into #304 too? I suspect it has something to do with this code.

**Comment by Androbin** [comment]
Will try to reproduce the issue before and after these fixes.

**Comment by shardulc** [comment]
The issue is about signs: PST is offset from UTC by -8 hours, not +8 as the issue shows.

**Comment by Androbin** [comment]
Interesting, the scraping code should be agnostic of the sign and let `float(text)` handle that.

**Comment by Androbin** [comment]
Interesting, this code is agnostic of the sign and should work either way.
But I suspect that the other scraping code has a problem due to the behavior of `int(offset)`.

**Comment by Androbin** [comment]
I'll try to find out if this is about scraping or displaying.

**Comment by Androbin** [comment]
node

**Comment by Androbin** [comment]
By the way, anything left to do for this PR?

**Comment by shardulc** [comment]
It would be nice if you found a way around the PST issue, and also the IST issue (does that also have the same problem?).

**Comment by Androbin** [comment]
@shardulc Since both are (in theory) equally right, we could either:
* Hardcode which variant we want
* Record both values and ask the user

**Comment by Androbin** [comment]
By the way, anything left to do for this PR?

**Comment by shardulc** [comment]
We could also record and print both times whenever there is ambiguity. This would involve parsing the [second column](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations) too. Can you make it part of this PR?

**Comment by Androbin** [comment]
I'd rather open a new one. But sure, I'll do.

**Comment by jonorthwash** [comment]
Currently getting an error: 
  File "/home/begiak/phenny/modules/clock.py", line 290, in scrape_wiki_zones
    if column == column_names.index('TZ'):
ValueError: 'TZ' is not in list

**Comment by sushain97** [comment]
^ that error is after I changed .find to .index because I thought that might have been the only error (didn't see this PR)

**Comment by jonorthwash** [comment]
This PR seems to fix the error :)

**Comment by jonorthwash** [comment]
Now we get this behaviour:
```
(00:41:45) firespeaker: .time Swarthmore
(00:41:45) begiak: firespeaker: Sorry, I don't know about the '%s' timezone.
```

**Comment by Androbin** [comment]
Yeah, #321

**Pull request merged**
