### PR TITLE
Fixed the 'module' object has no attribute 'Grab' Error (Google Code-In)

### PR DESCRIPTION
**Pull request by necessary129**
Well, That was easy, I don't know how phenny works, but i think i have done it.
I will try to work on other tasks as well :D

### CODE REVIEW

**Comment by sushain97** [comment]
Can you try to figure out why this was commented out? Perhaps using `git blame`.

**Comment by necessary129** [comment]
@sushain97 It was commented out for Google Code-in contest ([GCI][1])
[1]: https://developers.google.com/open-source/gci/

**Comment by sushain97** [comment]
I understand that it's been uncommented for GCI. However, why was it commented out in the first place?Furthermore, have you tested your changes with your own instance of phenny?

**Comment by necessary129** [comment]
@sushain97 39552930f42b1a19a35662c40942233842f6f2f4 seems to be the commit that changed it and yes, i have tested it (only the .randquote function though)

**Comment by sushain97** [comment]
That particular commit is more or less a merge commit, the actual changes would have taken place in an earlier commit.

**Comment by necessary129** [comment]
True, but i can't seem to find the branch/fork from which it was committed

**Comment by necessary129** [comment]
@jonorthwash It is done! I have tested it, and it works! so...

**Comment by jonorthwash** [comment]
Please remove commit 3ddeb2e from this pull request so that we can merge it!

**Comment by wei2912** [comment]
I will merge this PR after https://github.com/goavki/phenny/pull/153 is finished and merged.

**Comment by jonorthwash** [comment]
Could you merge it first, so that modification of fs_quotes is part of that task?

**Comment by wei2912** [comment]
True, I forgot about that. Will merge it in now.

**Comment by wei2912** [comment]
Merged in https://github.com/goavki/phenny/commit/5fa45f308a8478c0af3e30a4b3739d7cec893817 to https://github.com/goavki/phenny/commit/9da63cc7f3ff93f2e2f91b00115fecd79b7d7428

**Pull request closed without merging**
