### PR TITLE
Fixed username.

### PR DESCRIPTION
**Pull request by gstark0**

### CODE REVIEW

**Comment by gstark0** [comment]
@jonorthwash Well, this was hard coded before I integrated autocoverage with begiak, I just did this considering previous state of the code, thought it will be fine. But if you want, I can change that to get the username from config file?

**Comment by jonorthwash** [comment]
That would probably be the ideal solution.  An intermediate solution would be to at least set the username as a variable within the scope of this module instead of having it hard-coded twice(?).

**Comment by gstark0** [comment]
@jonorthwash Okay, I changed it, you should now create variable in config called "stemCounterBotLogin" and assign it to login :) Also I noticed syntax error in git.py, so I fixed it too.

**Comment by Androbin** [comment]
@gstark0 Your PR is based on b416d461dfc7a140b70a09cbab67bb5433f37b5a which is before 4f985e01120d26f5600d6d96b0ddc12e771779e2.
Try rebasing your PR on current master.

**Comment by gstark0** [comment]
@Androbin It doesn’t matter, these are the only changes made here.

**Comment by shardulc** [comment]
Since the repository behind this is no longer accessible, the changes have been moved to #309.

**Pull request closed without merging**
