### PR TITLE
Add maxlength to phenny.config (new)

### PR DESCRIPTION
**Pull request by galiaxy**
This is basically just a copy of #237 . I couldn't merge the commits from master, so I decided to make a new branch.

Edit: The Travis_CI bulild is still; red. It said `NameError: name 'phenny' is not defined`. What could've gone wrong?

### CODE REVIEW

**Comment by shardulc** [comment]
@reallyly The name `phenny`, as suggested by the error, is undefined. For example, in [this function](https://github.com/reallyly/phenny/blob/298c4ace7b6338f7bb2430eb703b9e12b9cffacf/modules/wikipedia.py#L80), note how `phenny` is passed as an argument, but in [the error-giving function](https://github.com/reallyly/phenny/blob/298c4ace7b6338f7bb2430eb703b9e12b9cffacf/modules/wikipedia.py#L45), it is absent.

The main file, which is `bot.py` if I recall correctly, registers all the modules and their regexes and passes the `phenny` parameter to them whenever the commands are invoked, which allows them to access and change the current state of the bot. Hope this helps!

**Comment by reallyly** [comment]
Oh.. I see.. But, in `bot.py`, where should I add `config.maxlength`?

**Comment by shardulc** [comment]
9c6a94e is partially correct, but it's in the wrong place. The parameter `maxlength`, or maybe `MAX_LENGTH`, should be something like [this](https://github.com/goavki/phenny/blob/master/phenny#L47) and also in your local copy of `~/.phenny/default.py`.

**Comment by reallyly** [comment]
Oh no, it has been months and I still haven't finished this :(. I am really sorry but I'm still not sure about where to make the variable :(

**Comment by wei2912** [comment]
@reallyly hmm, I've been really busy these past few weeks and haven't been able to attend to this. Could you come onto the IRC channel and seek guidance?

**Comment by reallyly** [comment]
Sorry for the late reply again. I've been quite busy too lately :(. Yeah okay, I'll try to come to IRC whenever I have chance.

**Comment by wei2912** [comment]
@galiaxy hi, would you like to free up this task for the GCI students this year, or continue to work on it?

**Comment by galiaxy** [comment]
@wei2912 I think I can't work on this anymore, sorry. I hope it's okay with you.

**Comment by wei2912** [comment]
It's alright, thanks for letting me know!

**Pull request closed without merging**
