### PR TITLE
Improve Wikipedia queries

### LINKED ISSUE #152: Wikipedia pages/sections that return bad results when queried by begiak
begiak doesn't work well on these 12 Wikipedia pages and 3 Wikipedia section examples I have found, and these can be generalized into 4 cases as described below. The sample output of the examples can be found in this paste: http://paste2.org/nXM7k8wV
## Case 1: Out of Place Fullstop problem

_Affected URLs_: https://en.wikipedia.org/wiki/Samuel_Johnson
                    https://en.wikipedia.org/wiki/Luca_Pacioli
                    https://en.wikipedia.org/wiki/Retina
                    https://en.wikipedia.org/wiki/Romance_languages
                    https://en.wikipedia.org/wiki/Origin_of_the_name_%22Empire_State%22
            https://en.wikipedia.org/wiki/Capon_Lake_Whipple_Truss_Bridge#Whipple_truss_development
https://ru.wikipedia.org/wiki/Путин,_Владимир_Владимирович
This problem occurs when the article has a period in its first sentence that was not supposed to end the sentence. For example,  periods in "e.g.", "c.", "A.D.", "U.S.", "O.S.", will end begiak/phenny's result prematurely when in the first sentence of the article's description. 
_Example:_<darkgaia> .wik Retina
<begiak> "The retina (/ˈrɛtɪnə/ RET-i-nə, pl" - https://en.wikipedia.org/wiki/Retina
## Case 2: 'NoneType object"

_Affected URLs_: https://en.wikipedia.org/wiki/Main_Page
                    https://en.wikipedia.org/wiki/1990_United_States_Census#State_rankings
https://en.wikipedia.org/wiki/Calendar#Further_reading
This problem appears to occur strikingly on the Main Page, and more commonly in sections, where there is a broad user interface as such, interfering with begiak/phenny's wiki module. 
image
_Example:_<darkgaia> .wik Main_Page
<begiak> AttributeError: 'NoneType' object has no attribute 'text_content' (file "/home/begiak/phenny/modules/wikipedia.py", line 67, in parse_wiki_page)
## Case 3: Right-side extraneous information

_Affected URLs_: https://en.wikipedia.org/wiki/59th_Street_(Manhattan)
                    https://en.wikipedia.org/wiki/East_Harlem
                    https://en.wikipedia.org/wiki/NATO
                    https://en.wikipedia.org/wiki/Broadway_(Manhattan)
This problem occurs strikingly when there are "Coordinates" on the top right hand of an article for a location. However, this appears not to be a problem for some other articles with "Coordinate" information, including https://en.wikipedia.org/wiki/New_York_City, https://en.wikipedia.org/wiki/Chinatown,_Manhattan, https://en.wikipedia.org/wiki/Empire_State_Building. It is unknown what causes this difference in output.
_Example:_<darkgaia> .wik 59th Street (Manhattan)
<begiak> "Coordinates: 40°46′09″N 73°59′05″W﻿ / ﻿40.769212°N 73.984772°W﻿ / 40.769212; -73.984772" - https://en.wikipedia.org/wiki/59th_Street_(Manhattan)
image
image
## Case 4: Non-decriptive First Sentence.

Affected URLs: https://en.wikipedia.org/wiki/Sex_differences_in_humans
This appears to be more of a problem with the article itself than the begiak/phenny module. When the article's first sentence is not descriptive of the article, rather, the description is in the second sentence, a poor result will invariably be returned. 
_Example:_ <darkgaia> .wik Sex differences in humans
<begiak> "Sex differences in humans have been studied in a variety of fields" - https://en.wikipedia.org/wiki/Sex_differences_in_humans

### PR DESCRIPTION
**Pull request by Androbin**
Fixes #152 Case 1 and 3

### CODE REVIEW

**Comment by Androbin** [comment]
@shardulc @sushain97 Friendly ping.

**Comment by shardulc** [comment]
I am not too satisfied with this solution. I believe using [the actual MediaWiki API](https://en.wikipedia.org/w/api.php?action=help&modules=query%2Bextracts) is a much better approach. The linked API endpoint is meant to get extracts of Wikipedia pages and would solve most if not all of #152.

**Comment by shardulc** [comment]
Further, if the MediaWiki API can be implemented on Apertium's wiki too, it would similarly deal with #151.

**Comment by Androbin** [comment]
Just noticed that someone else had the abbreviation blacklist idea first:
https://github.com/goavki/phenny/commit/ec32741826e9cf039bf014f79fee0506f1ef6725#diff-aa0bf3058854ba2d1180b714f03d23beL31

**Pull request closed without merging**
