### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by Androbin**
* `eleda`, `linx`: `CRLF` -> `LF`
* `functions`: unused -> removed

@shardulc /cc

### CODE REVIEW

**Comment by shardulc** [comment]
The only concern I have is that changing the entire file makes `git blame` problematic. I think we should wait for @jonorthwash or @sushain97 on this.

**Comment by jonorthwash** [comment]
I don't care that much.  Let's see what @sushain97 says.

**Comment by sushain97** [comment]
This is fine as a one off change. However, there's a way to enforce this via gitconfig that would be nice to add since the repo has many Windows contributors. Coul you add this, @Androbin? Then, it could be merged all at once.

**Comment by Androbin** [comment]
> However, there's a way to enforce this via gitconfig that would be nice to add since the repo has many Windows contributors.

@sushain97 I have added the relevant `.gitattributes` file.

**Pull request merged**
