### PR TITLE
Refactor bot.py logging

### PR DESCRIPTION
**Pull request by Androbin**
Split from / Depends on #310

### CODE REVIEW

**Comment by Androbin** [comment]
@sushain97 Friendly ping.

**Comment by Androbin** [comment]
@sushain97 Friendly ping.

**Comment by sushain97** [comment]
This was reverted due to the following:

```
firespeaker:     self.bind_commands()
[11:35pm] firespeaker:   File "/home/begiak/phenny/bot.py", line 182, in bind_commands
[11:35pm] firespeaker:     for name, func in functions.items():
[11:35pm] firespeaker: AttributeError: 'function' object has no attribute 'items'
[11:35pm] ryanchi: I think I’ll try committing now :|
[11:35pm] sushain: ugh I accepted that commit firespeaker
[11:35pm] sushain: my fault
[11:36pm] sushain: let me revert
[11:36pm] sushain: how are the tests passing when it doesn’t even actually start up...
[11:36pm] ryanchi: sushain: http://svn.code.sf.net/p/apertium/svn/incubator/ now has the three repos linked
[11:37pm] ryanchi: not sure how I’d test it, but jpn, ain, and yaq are all linked
[11:38pm] firespeaker: sushain: the weird thing is, it does start
[11:38pm] firespeaker: sushain: I get this when I close:
[11:38pm] sushain: ryanchi: let me test it
[11:38pm] firespeaker: ^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
[11:38pm] firespeaker: Traceback (most recent call last):
[11:38pm] firespeaker:   File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
```

cc @jonorthwash

**Comment by Androbin** [comment]
Probably an issue with reloading. Seems like I forgot something.

**Pull request merged**
