### PR TITLE
Resolve issues with git.py

### LINKED ISSUE #334: updated begiak is screwed up with untested broken code
When starting begiak cold, we now get this:

```
ERROR: Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 224, in call
    try: func(phenny, input)
  File "/home/begiak/phenny/modules/git.py", line 380, in setup_server
    httpd = socketserver.TCPServer(("", PORT), Handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

ERROR: Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 224, in call
    try: func(phenny, input)
  File "/home/begiak/phenny/modules/git.py", line 380, in setup_server
    httpd = socketserver.TCPServer(("", PORT), Handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

ERROR: Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 224, in call
    try: func(phenny, input)
  File "/home/begiak/phenny/modules/git.py", line 380, in setup_server
    httpd = socketserver.TCPServer(("", PORT), Handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

ERROR: Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 224, in call
    try: func(phenny, input)
  File "/home/begiak/phenny/modules/git.py", line 380, in setup_server
    httpd = socketserver.TCPServer(("", PORT), Handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

We also get the following:

```
INFO: Nobody PONGed our PING, restarting
INFO: Closed!
WARNING: Disconnected. Reconnecting in 20 seconds...
```

Begiak then disconnects and reconnects.

@gstark0 @androbin

### PR DESCRIPTION
**Pull request by Androbin**
Hopefully fixes #334 
See https://github.com/goavki/phenny/issues/334#issuecomment-355751956 for reference
@jonorthwash /cc

### CODE REVIEW

**Comment by gstark0** [comment]
Wait a sec, I will check this on Begiak.

**Comment by gstark0** [comment]
@Androbin Im getting error running this:
`ERROR: Error loading git: [Errno 22] Invalid argument (in bot.py)`
Although seems like traceback is gone.

**Comment by Androbin** [comment]
@gstark0 Seems like you can't catch `SIGKILL`, unfortunately.
But `SIGTERM` is usually triggered right before it anyway.

**Comment by Androbin** [comment]
Really, have you tried without `SIGKILL` ?
Because then it works for me.

**Comment by gstark0** [comment]
@Androbin Yes, I checked out your pull request 10 seconds ago to server, the error above is gone, but traceback appeared again.

**Comment by Androbin** [comment]
Can you check if the exit handler is run when you kill the program?

**Comment by gstark0** [comment]
@Androbin During testing this solution, I found out something interesting, this doesn't show errors when running in #apertium_testing channel.

**Comment by Androbin** [comment]
The multiple channel thing could be due to `setup_server` being called more than once.
Note that it's triggered by the `MODE` event.

**Comment by gstark0** [comment]
@Androbin Yeah I thought about the same looking at the code. The thing with multiple channels is pretty good hint for this issue.

**Comment by Androbin** [comment]
@gstark0 The exit handler is called for me (Ctrl+C)
Can you double-check your `print` statements?
Maybe it's an OS thing?

**Comment by Androbin** [comment]
Do you think the reconnect (which reruns all setup functions and re-registers all modules) might cause the server to be started multiple times?

**Comment by Androbin** [comment]
@gstark0 Can you reproduce the issue with b87aa4c1cb8326442c6276c294cc8255ed479a52 ?

**Comment by Androbin** [comment]
@jonorthwash I have tested this PR. Even if there is some blind spot left, it should only help things.

**Pull request merged**
