### PR TITLE
Encapsulate magic number 430

### LINKED ISSUE #213: Magic number 430 used to represent maximum message length
In many of begiak's modules, the constant 430 is used to represent the maximum message length, however its use can be confusing for code maintainers. I suggest that a constant, `MAX_MSG_LEN`, be placed in the config file and have all instances of constants representing message length be replaced.

### PR DESCRIPTION
**Pull request by Androbin**
Fixes #213
Uses #284

### CODE REVIEW

**Comment by sushain97** [comment]
Looks like this results in legitimate test failure: https://travis-ci.org/goavki/phenny/jobs/322739077#L658

**Comment by Androbin** [comment]
Oops, the flawky code is on master. #297 should fix it.

**Comment by Androbin** [comment]
Okay, errors are fixed.

**Comment by shardulc** [comment]
You can remove the TODO message from `tools.py` now.

**Comment by shardulc** [comment]
Further, as all the config options are lowercase and spelled out, I suggest that `MAX_MSG_LEN` be changed to `max_message_length`.

**Comment by Androbin** [comment]
Almost forgot about it.

**Comment by Androbin** [comment]
Only the config key name or the global name as well?

**Comment by shardulc** [comment]
The global name is used only in `tools.py`, right? Then you can rename it too.

**Comment by jonorthwash** [comment]
Still getting stuff like this:
```
(20:49:35) begiak: firespeaker: 01:19Z <jjjppp> tell firespeaker my question about the 2-3 letter code conflation was that you asked me for the task to create an algorithm that "generate 2-to-3-letter mappings for available languages based on having the identical language name in languages.json instead of loading the huge list from codes.json; try to make this as processor- and memory-efficient as possible." However, the codes.json file is
(20:49:36) begiak: actually quite small
```

**Comment by Androbin** [comment]
What's wrong with it?

**Comment by jonorthwash** [comment]
It may not be related exactly to this issue, but is the same sort of issue.  We probably need to consider how to deal with messages that are shorter than the max message length but will output larger than it (or whether to even make them that much longer in the first place).  We probably also want a datestamp in these messages and not just a timestamp??

**Comment by Androbin** [comment]
We already have this discussion on #318 @shardulc /cc.

**Comment by Androbin** [comment]
Such issues should fall into two basic categories:
* The available length is known at the time of splitting
* The length depends on unknown future circumstances

The first case should be easy to resolve and depends on which module splits the message and which module appends to the message.

The seconds case may be trickier, but may also be as simple as #338.

**Pull request merged**
