### PR TITLE
Fix google search

### PR DESCRIPTION
**Pull request by jatinluthra14**

### CODE REVIEW

**Comment by wei2912** [comment]
Could you update the tests to ensure that it passes?

**Comment by jatinluthra14** [comment]
Update tests?

**Comment by wei2912** [comment]
Yes, test_search.py

**Comment by jatinluthra14** [comment]
Okay Let me see. PLease join #jatinluthra14 for testing of search module

**Comment by jatinluthra14** [comment]
@wei2912 Updated tests. Now Won't fail

**Comment by wei2912** [comment]
But the build just failed? :P

**Comment by jatinluthra14** [comment]
Hey the vtluug test failed not mine. See Travis logs. Shardulc has explanation for it too see irc

**Comment by wei2912** [comment]
Alright, thanks for the clarification.

**Pull request merged**
