### PR TITLE
Fix truncate bugs

### PR DESCRIPTION
**Pull request by Androbin**
Introduced in #284

### CODE REVIEW

**Comment by Androbin** [comment]
@wei2912 Friendly ping.

**Comment by Androbin** [comment]
@sushain97 Friendly ping.

**Comment by Androbin** [comment]
@sushain97 Would you mind?

**Comment by sushain97** [comment]
I haven't been super involved in this conversation so I need a summary of what these changes actually do. Also, build seems to be failing?

**Comment by Androbin** [comment]
During #284 I forgot to apply the encoding/decoding to `truncate` as well.

**Comment by sushain97** [comment]
> During #284 I forgot to apply the encoding/decoding to truncate as well.

This diff appears to be far more than just encoding changes.

**Comment by Androbin** [comment]
> This diff appears to be far more than just encoding changes.

Yeah, I thought I'd take the opportunity to refactor a bit.
As long as the tests pass, it should be at least as merge-able as #284.

**Comment by Androbin** [comment]
BTW. For some reason, only 3.6 is failing?

**Comment by sushain97** [comment]
> Yeah, I thought I'd take the opportunity to refactor a bit.

Sure, that's fine but then I need some context on/summary of everything else that's happening.

**Comment by Androbin** [comment]
* Reorder the parameters of `truncate`
* Pass `share` instead of it's length `extra_space`
* Factor out `encodeIfNot`
* Use `encodeIfNot` and `.decode('utf-8', 'ignore')` in `truncate` as well
* `text <= max_length` -> `len(text) <= max_length`

**Comment by Androbin** [comment]
This PR should also unblock #295.

**Comment by Androbin** [comment]
@sushain97 I fixed the flawky test. Had to revert 9db4cdc898eaf2ca1a6096c311bdae0f1a637c83.

**Comment by Androbin** [comment]
@wei2912 @sushain97 Can someone take a look?

**Comment by shardulc** [comment]
As usual, screenshots please to ensure this works. How come the screenshots on #284 didn't show this behavior?

**Comment by Androbin** [comment]
Because #284 was between #286 and #291.

**Comment by Androbin** [comment]
Gimme a minute to do some testing.

**Comment by Androbin** [comment]
screenshot

**Comment by sushain97** [comment]
This looks alright to me but I'd like @shardulc to take a look since he's been more active on this issue.

**Pull request merged**
