### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by mathematic-alpha**

### CODE REVIEW

**Comment by unhammer** [comment]
Zero lines changed? What's this all about?

**Comment by mathematic-alpha** [comment]
Open a pull request to merge features from begiak (Apertium's IRC bot) into upstream

**Comment by unhammer** [comment]
@mathematic-alpha this doesn't actually include any changes

**Comment by wei2912** [comment]
@mathematic-alpha By merging features from begiak into upstream, we're referring to takeing changes from https://github.com/goavki/phenny/ and merging it into https://github.com/mutantmonkey/phenny. Also, for empty commits that you encounter while cherry picking, you should skip the commit so that there are no empty commits present in the log.

@unhammer I think @mathematic-alpha is confused about https://codein.withgoogle.com/task-instances/5384492019613696/. This PR can be closed.

**Pull request closed without merging**
