### PR TITLE
Drop scraped +/-X entries

### LINKED ISSUE #360: .time spams whole chat now
@shardulc @sushain97 
Using `.time` command will spam whole chat, if this is intended, it's super useless IMHO :
screen shot 2018-01-09 at 07 20 51
screen shot 2018-01-09 at 07 20 43

### PR DESCRIPTION
**Pull request by Androbin**
Fixes #360 
@gstark0 /cc
@sushain97 /cc

### CODE REVIEW

**Comment by sushain97** [comment]
What functionality will this eliminate?

**Comment by Androbin** [comment]
> What functionality will this eliminate?

In theory, none. Since we already handle the `+/-X` notation for all timezones, we should not lose any functionality. But this would resolve the conflict between the custom handling and the scraped entries already including such variants.

**Comment by Androbin** [comment]
Maybe we can even move our custom handling from `give_time` to `get_offsets`.

**Comment by sushain97** [comment]
> In theory, none.

Some tests would be good to support that assertion.

**Comment by Androbin** [comment]
screenshot

**Comment by Androbin** [comment]
Includes #380

**Comment by Androbin** [comment]
Tests show that that the syntax still works.

**Comment by sushain97** [comment]
Okay. Final change, let's go to one line of comma separated responses.

**Comment by Androbin** [comment]
Shall we use another time format then? For example, we really don't need to print month/year thrice.

**Comment by sushain97** [comment]
What if it's near the end of a month and the time zones are in different
months? Or even years.

On Jan 19, 2018 9:10 AM, "Robin Richtsfeld" <notifications@github.com>
wrote:

Shall we use another time format then? For example, we really don't need to
print month/year thrice.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/goavki/phenny/pull/378#issuecomment-358992729>, or mute
the thread

**Comment by Androbin** [comment]
screenshot

**Comment by Androbin** [comment]
I don't see the benefit in the last change.

**Comment by Androbin** [comment]
@sushain97 Could you explain the supposed benefit of the last change?

**Comment by sushain97** [comment]
The three lines is spammy and has been criticized on IRC.

**Comment by Androbin** [comment]
> The three lines is spammy and has been criticized on IRC.

As far as I remember, the dozen lines were considered spammy.
But as of #377 this should no longer be a problem?

**Pull request merged**
