### PR TITLE
Fix TypeError

### PR DESCRIPTION
**Pull request by Androbin**
`TypeError: Can't convert 'bytes' object to str implicitly (file "/home/begiak/phenny/modules/apertium_wiki.py", line 86, in apertium_wiki)`

Seems like I messed up on the last change to this code.

### CODE REVIEW

**Comment by jonorthwash** [comment]
When I merged this, I got the following error:
```
(15:30:21) begiak: Something went wrong: dict_keys(['pusher', 'ref', 'repository', 'sender', 'deleted', 'organization', 'base_ref', 'after', 'before', 'compare', 'head_commit', 'commits', 'forced', 'created'])
```

**Comment by Androbin** [comment]
This is unrelated. Should already be fixed.

**Comment by Androbin** [comment]
The `git.py` is known to refuse to reload properly.

**Comment by jonorthwash** [comment]
No, this error had nothing to do with reloading.  There were correct git notifications before and after this message.

**Comment by Androbin** [comment]
I remember to have fixed that error. It needs certain circumstances too appear.
Seems like begiak didn't reload with the bug fix.

**Comment by jonorthwash** [comment]
Where (in which PR) was the fix?

**Comment by Androbin** [comment]
commit 11179e7bb6631a3a6fc1601fd3211a3f0ada1fb3 in PR 306

**Comment by Androbin** [comment]
The error is reported by [this line](https://github.com/goavki/phenny/blob/master/modules/git.py#L338) when no messages were generated. Which was the case before that fix.

**Pull request merged**
