### PR TITLE
Fix tests again

### PR DESCRIPTION
**Pull request by shardulc**
Includes some small modifications to the search.py and apy.py modules.

### CODE REVIEW

**Comment by wei2912** [comment]
This seems to change APy behaviour. Could you clarify on this? A separate PR should be made.

**Comment by shardulc** [comment]
@wei2912 Yes, it changes the behavior of the apy module, as specified in [my comment](https://github.com/goavki/phenny/pull/235#commitcomment-20480850). I thought I should make a separate PR, but @jonorthwash had made some changes to the module in `master`, which broke some tests. Since I wanted to fix the tests, I discussed the intended behavior with him and changed the module some more so that the old syntax/functions were retained (and the tests could pass) while new functionality was added. Making a separate PR would have either required writing new tests here, which would be overwritten by the new PR, or letting them fail, which defeated the purpose.

**Comment by wei2912** [comment]
I'm honestly quite packed atm... Will do my best to review your PR within a
week.

**Comment by wei2912** [comment]
Looks alright to me, merging.

**Pull request merged**
