### PR TITLE
Add maxlength to phenny.config

### PR DESCRIPTION
**Pull request by reallyly**
I did this a while ago in GCI, and haven't submit a PR, yet. However, my task is approved. I'm not sure if this is enough but I promised to continue this even after GCI is finished, and I realized that I can't talk in the GCI task page anymore, so I'm just going to make a PR and I hope the mentors will respond here.

Thanks!

### CODE REVIEW

**Comment by reallyly** [comment]
.. although I'm not sure why my build is red.

**Comment by wei2912** [comment]
@reallyly Sorry, it took me a while to look at this. Is this for every module making use of the IRC maximum message length in some way?

**Comment by reallyly** [comment]
I'm pretty sure yeah. I've take a look to all the files in the repo - I just hope I didn't miss any.

Is there any way to fix my red Travis build?

**Comment by wei2912** [comment]
You could merge commits from master. Unfortunately, Travis seems to be having an issue where the build script fails sometimes, causing the overall build to error out. This happens on different builds with the same code, so it seems to be a Travis issue. We'll have to wait for that to be fixed.

**Comment by reallyly** [comment]
Okay what should I do now then? Re-run the Travis?

**Comment by wei2912** [comment]
@reallyly Yes.

**Comment by reallyly** [comment]
I'm sorry for the very late respond, I was confused on how to merge the commits from master. 
So I made a new branch instead and make a PR from it. 

.. closing this PR ..

**Comment by wei2912** [comment]
Okay, thanks.

**Pull request closed without merging**
