### PR TITLE
Change Some Variables' Names Into Caps

### PR DESCRIPTION
**Pull request by reallyly**
I changed some variables' names into caps, because they're constant variables. Also, changed "maxlength" to "current_length" and assign it to MAX_LENGTH. 

(I hope to solve issue #213 for GCI)

### CODE REVIEW

**Comment by wei2912** [comment]
As mentioned in the issue,

> I suggest that a constant, MAX_MSG_LEN, be placed in the config file and have all instances of constants representing message length be replaced.

Take note that not all modules rely on the `irc.py` functionality. Some modules deliberately trim their messages when it reaches 430 characters. Please check through these modules and have them use the phenny config.

**Comment by reallyly** [comment]
Where can I find the config file? .... Or should I make a new one?

**Comment by wei2912** [comment]
Look in the file phenny.

**Comment by reallyly** [comment]
Oh I see. But I'm not sure how can I place the constant variable in the config file. I tried to understand the `phenny` file but it confuses me. Could you perhaps tell me some hints please?

**Comment by wei2912** [comment]
Could you come over to the IRC channel? We can discuss further over there.

**Comment by wei2912** [comment]
I've explained how to put a variable inside the config file, and how to access it. Now, look through the modules and see if you could replace `430`, or any other variations like `428 - len(input.nick())` to `max_msg_length` and `max_msg_length - len(input.nick()) - 2`.

**Pull request closed without merging**
